[package]
name = "test-zisk-verifier"
version = "0.1.0"
edition = "2021"
default-run = "test-zisk-verifier"

[dependencies]
ziskos = { path = "../ziskos/entrypoint" }
zisk-verifier = { path = "../verifier" }

[profile.release.package."proofman-verifier"]
opt-level = 0

[workspace]