[package]
name = "sha-hasher-host"
version = "0.1.0"
edition = "2024"

[dependencies]
zisk-sdk = { workspace = true }
zisk-common = { workspace = true }
anyhow = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = "0.10.8"

[build-dependencies]
zisk-build = { workspace = true }
zisk-common = { workspace = true }

[features]
default = []
packed = ["zisk-sdk/packed"]
gpu = ["zisk-sdk/gpu", "packed"]

[[bin]]
name = "prove"
path = "bin/prove.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "plonk"
path = "bin/plonk.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "verify-constraints"
path = "bin/verify-constraints.rs"