[package]
name = "zisk-build"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true

[dependencies]
clap = { workspace = true }
cargo_metadata = "0.23.0"
anyhow = { workspace = true }
tracing = { workspace = true }
rom-setup = { workspace = true }

[build-dependencies]
vergen-git2.workspace = true

[features]
disable_distributed = []