[package]
name = "sm-frequent-ops"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "frequent_ops_test"
path = "src/frequent_ops_test.rs"

[dependencies]
zisk-core = { workspace = true }

fields = { workspace=true }
proofman-common = { workspace = true }
proofman-util = { workspace = true }
tracing = { workspace = true }

clap = "4.0"
rayon = { workspace = true }
num-bigint = { workspace = true }
static_assertions = { workspace = true }

[features]
default = []
gpu = ["packed"]
packed = []
generate_code_arith_range_table = []